name: "Check Format"
author: "Kungfu Trader"
description: "Check code format"
inputs:
  token:
    description: "E.g. secrets.GITHUB_TOKEN"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
